# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'afnetworkingdemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for afnetworkingdemo
    pod 'AFNetworking', '~> 4.0'

end
